[web]
web-server ansible_host=localhost ansible_port=2210 ansible_user=root ansible_password=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[app]
app-server ansible_host=localhost ansible_port=2211 ansible_user=root ansible_password=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[db]
db-server ansible_host=localhost ansible_port=2212 ansible_user=root ansible_password=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
